#!/usr/bin/env python3
"""Generate bilingual, accessible SVG diagrams from ICH_Seminar_Anis8BIS.

Figures 1–4 redraw slides 1–3. Figure 5 explicitly synthesises slide 4's text.
No experimental data or quantitative result is generated by this script.
"""
from pathlib import Path
from html import escape

OUT = Path(__file__).resolve().parents[1] / 'assets' / 'figures'
OUT.mkdir(parents=True, exist_ok=True)
INK, ACCENT, PAPER = '#172b3a', '#315b60', '#faf9f6'

class Figure:
    def __init__(self, name, lang, title, desc, width, height):
        self.name, self.lang = name, lang
        self.parts = [f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title description" xml:lang="{lang}" lang="{lang}">
<title id="title">{escape(title)}</title><desc id="description">{escape(desc)}</desc>
<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="{ACCENT}"/></marker></defs>
<rect width="100%" height="100%" fill="{PAPER}"/>
<g font-family="Arial, Helvetica, sans-serif" font-size="22" fill="{INK}">''']
    def text(self, x, y, lines, size=22, anchor='middle', weight='normal', color=INK):
        if isinstance(lines,str): lines=[lines]
        self.parts.append(f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-size="{size}" font-weight="{weight}" fill="{color}">')
        for i,line in enumerate(lines):self.parts.append(f'<tspan x="{x}" dy="{0 if i==0 else size*1.35}">{escape(line)}</tspan>')
        self.parts.append('</text>')
    def box(self,x,y,w,h,lines,dark=False,ellipse=False,size=22):
        bg,fg=(INK,'#ffffff') if dark else ('#eef2ef',INK)
        if ellipse:self.parts.append(f'<ellipse cx="{x+w/2}" cy="{y+h/2}" rx="{w/2}" ry="{h/2}" fill="{bg}" stroke="{ACCENT}" stroke-width="2"/>')
        else:self.parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="3" fill="{bg}" stroke="{ACCENT}" stroke-width="2"/>')
        if isinstance(lines,str):lines=[lines]
        self.text(x+w/2,y+h/2-(len(lines)-1)*size*.675+size*.34,lines,size=size,color=fg)
    def line(self,points,arrow=True,dashed=False):
        self.parts.append(f'<path d="{points}" fill="none" stroke="{ACCENT}" stroke-width="2.5"'+(' marker-end="url(#arrow)"' if arrow else '')+(' stroke-dasharray="7 6"' if dashed else '')+'/>')
    def save(self):
        (OUT/f'{self.name}-{self.lang}.svg').write_text('\n'.join(self.parts+['</g></svg>'])+'\n')

def make(lang):
    fr=lang=='fr'
    def t(a,b):return a if fr else b
    f=Figure('image-processing',lang,t('Adaptation granulaire des images','Granular image adaptation'),t('Une image couleur alimente la granulation variable et l’interpolation. La décomposition produit deux granules, utilisés pour interpoler les couleurs et sélectionner le premier plan. Le granule de premier plan et un facteur de réduction alimentent la construction du SVG tactile.','A colour image feeds variable granulation and interpolation. Decomposition produces two granules used for colour interpolation and foreground selection. The foreground granule and a shrink factor feed tactile SVG construction.'),1120,770)
    f.text(32,38,t('01 / IMAGE, GRANULES ET RESTITUTION','01 / IMAGE, GRANULES AND OUTPUT'),size=18,anchor='start',weight='bold')
    # Preserve the two routes from the source and both branches from decomposition.
    f.line('M 175 140 L 250 140');f.line('M 100 105 L 100 72 L 620 72 L 620 106')
    f.line('M 395 192 L 395 242');f.line('M 395 296 L 395 340');f.line('M 540 388 L 635 388')
    f.line('M 702 352 L 702 192');f.line('M 835 148 L 880 148 L 880 117 L 910 117');f.line('M 880 148 L 880 207 L 910 207')
    f.line('M 702 425 L 702 489');f.line('M 795 540 L 852 540');f.line('M 925 578 L 925 610 L 860 610 L 860 645 L 815 645')
    f.line('M 205 668 L 575 668');f.line('M 815 698 L 905 698')
    f.box(25,105,150,90,t(['Image couleur','(RVB)'],['Colour image','(RGB)']))
    f.box(250,105,290,87,t(['1. Granulation','variable'],['1. Variable','granulation']),True)
    f.box(340,242,110,54,'Y')
    f.box(250,340,290,96,t(['2. Décomposition','des granules'],['2. Granule','decomposition']),True)
    f.box(635,352,135,73,t(['Deux','granules'],['Two','granules']))
    f.box(560,106,275,86,t('3. Interpolation','3. Interpolation'),True)
    f.box(910,82,185,72,t(['Couleur du','premier plan'],['Foreground','colour']),size=20)
    f.box(910,172,185,72,t(['Couleur de','l’arrière-plan'],['Background','colour']),size=20)
    f.box(335,489,460,105,t(['4. Sélection du premier plan','selon les relations entre granules'],['4. Foreground selection','based on granule relationships']),True)
    f.box(852,499,220,79,t(['Granule de','premier plan'],['Foreground','granule']),size=20)
    f.box(25,627,180,86,t(['Facteur de','réduction'],['Shrink','factor']))
    f.box(575,625,240,113,t(['5. Construction','des granules'],['5. Granule','construction']),True)
    f.box(905,660,190,76,t('SVG tactile','Tactile SVG'))
    f.save()

    f=Figure('image-use-cases',lang,t('Exploration personnalisée d’une image','Personalised image exploration'),t('Les personnes voyantes et aveugles peuvent explorer l’image sur écran tactile. Deux extensions permettent de personnaliser la granularité graphique et la granularité haptique.','Sighted and blind users can explore the image on a touchscreen. Two extensions customise graphic granularity and haptic granularity.'),1100,650)
    f.text(32,38,t('02 / EXPLORATION ET PERSONNALISATION','02 / EXPLORATION AND CUSTOMISATION'),size=18,anchor='start',weight='bold')
    f.line('M 242 151 L 470 216',False);f.line('M 242 329 L 470 271',False)
    f.line('M 447 476 L 620 327',True,True);f.line('M 844 476 L 795 328',True,True)
    f.box(30,113,212,80,t(['Personne','voyante'],['Sighted','user']))
    f.box(30,289,212,80,t(['Personne','aveugle'],['Blind','user']))
    f.box(470,144,580,202,t(['Explorer l’image','sur un écran tactile'],['Explore the image','on a touchscreen']),True,True,size=26)
    f.box(190,477,435,135,t(['Personnaliser la','granularité graphique'],['Customise','graphic granularity']),ellipse=True)
    f.box(650,477,425,135,t(['Personnaliser la','granularité haptique'],['Customise','haptic granularity']),ellipse=True)
    f.text(438,411,'«extend»',size=18);f.text(902,411,'«extend»',size=18)
    f.text(32,635,t('Les flèches en pointillés désignent les extensions du cas d’utilisation.','Dashed arrows denote use-case extensions.'),size=18,anchor='start')
    f.save()

    f=Figure('granularity-mechanisms',lang,t('Mécanismes multi-granulaires','Multi-granularity mechanisms'),t('La représentation multi-granulaire permet l’optimisation du niveau, la conversion entre niveaux et la résolution conjointe mobilisant tous les niveaux.','Multi-granular representation supports level optimisation, conversion between levels and joint problem solving using every level.'),1100,620)
    f.text(32,38,t('03 / MÉCANISMES DE GRANULARITÉ','03 / GRANULARITY MECHANISMS'),size=18,anchor='start',weight='bold')
    f.line('M 295 305 L 337 305 L 337 147 L 380 147');f.line('M 337 305 L 380 305');f.line('M 337 305 L 337 477 L 380 477')
    f.box(25,247,270,116,t(['Représentation','multi-granulaire'],['Multi-granular','representation']),True)
    rows=[(93,t(['Optimisation','de la granularité'],['Granularity','optimisation']),t(['Choisir le niveau','le plus adapté'],['Choose the most','suitable level'])),(247,t(['Conversion','de granularité'],['Granularity','conversion']),t(['Passer entre niveaux voisins','ou à un niveau supérieur','ou inférieur'],['Switch between adjacent levels','or jump to a higher','or lower level'])),(421,t(['Résolution conjointe','multi-granulaire'],['Joint multi-granularity','problem solving']),t(['Mobiliser tous','les niveaux'],['Use every','level']))]
    for y,a,b in rows:
        f.box(380,y,300,112,a);f.line(f'M 680 {y+56} L 725 {y+56}');f.box(725,y,350,112,b,size=20)
    f.save()

    f=Figure('granular-computing',lang,t('Dimensions du calcul granulaire','Dimensions of granular computing'),t('Le calcul granulaire associe pensée structurée, traitement structuré de l’information et résolution structurée des problèmes.','Granular computing brings together structured thinking, structured information processing and structured problem solving.'),1000,550)
    f.text(32,38,t('04 / CALCUL GRANULAIRE','04 / GRANULAR COMPUTING'),size=18,anchor='start',weight='bold')
    f.line('M 500 198 L 500 254',False);f.line('M 400 349 L 271 418',False);f.line('M 600 349 L 729 418',False)
    f.box(350,85,300,113,t(['Pensée','structurée'],['Structured','thinking']))
    f.box(350,254,300,100,t(['Calcul','granulaire'],['Granular','computing']),True)
    f.box(35,418,435,104,t(['Traitement structuré','de l’information'],['Structured','information processing']))
    f.box(530,418,435,104,t(['Résolution structurée','des problèmes'],['Structured','problem solving']))
    f.save()

    f=Figure('fatigue-multimodal',lang,t('Analyse multimodale de la fatigue','Multimodal fatigue analysis'),t('Les expressions faciales, mouvements oculaires et autres indices visuels sont analysés par vision par ordinateur. Les données de fréquence cardiaque, pression artérielle et saturation en oxygène apportent des indicateurs complémentaires au modèle d’apprentissage automatique pour étudier la fatigue chez les personnes âgées.','Computer vision analyses facial expressions, eye movements and other visual cues. Heart rate, blood pressure and oxygen saturation provide complementary indicators to the machine learning model for studying fatigue in older adults.'),1100,620)
    f.text(32,38,t('05 / SOURCES COMPLÉMENTAIRES POUR L’ANALYSE','05 / COMPLEMENTARY SOURCES FOR ANALYSIS'),size=18,anchor='start',weight='bold')
    f.line('M 462 179 L 600 179 L 600 325 L 735 325');f.line('M 462 438 L 600 438 L 600 325',False);f.line('M 890 376 L 890 490')
    f.box(30,91,432,181,t(['Vision par ordinateur','Expressions faciales','Mouvements oculaires','Autres indices visuels'],['Computer vision','Facial expressions','Eye movements','Other visual cues']))
    f.box(30,345,432,184,t(['Mesures physiologiques','Fréquence cardiaque','Pression artérielle','Saturation en oxygène'],['Physiological measures','Heart rate','Blood pressure','Oxygen saturation']))
    f.box(735,264,335,112,t(['Modèle d’apprentissage','automatique'],['Machine learning','model']),True)
    f.box(735,490,335,95,t(['Analyse de la fatigue','chez les personnes âgées'],['Fatigue analysis','in older adults']),size=21)
    f.text(32,604,t('Synthèse du texte de la diapositive 4 ; aucun résultat expérimental n’est représenté.','Synthesis of slide 4’s text; no experimental result is depicted.'),size=17,anchor='start')
    f.save()

if __name__=='__main__':
    for lang in ['fr','en']:make(lang)
